using System;
using System.Collections.Generic;
using System.Text;

namespace Ongenet.Scripting.Export;

internal static class ScriptCodeGenerator
{
    public static string Header(string kind, string projectName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Ongenet — portable " + kind + " script (no audio PCM)");
        sb.AppendLine("// Re-run: Scripting tab → Run. Re-link audio paths marked TODO.");
        sb.AppendLine($"// Source: {EscapeComment(projectName)}");
        sb.AppendLine($"// Generated: {DateTime.UtcNow:O}");
        sb.AppendLine();
        sb.AppendLine("// Global api is IScriptingApi");
        return sb.ToString();
    }

    public static string GuidLiteral(Guid id) => $"new Guid(\"{id}\")";

    public static string StringLiteral(string? value) =>
        value is null ? "null" : "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n") + "\"";

    public static string DoubleLiteral(double value) =>
        double.IsNaN(value) || double.IsInfinity(value) ? "0.0" : value.ToString("R");

    public static string EscapeComment(string text) =>
        text.Replace("\r", " ").Replace("\n", " ");
}
