using System;
using System.Linq;
using Ongenet.Core.Audio.Effects;
using Ongenet.Core.Audio.Instruments;
using Ongenet.Core.Models.Audio;
using Ongenet.Core.Services;
using Ongenet.Scripting.Export;
using Xunit;

namespace Ongenet.Core.Tests.Services;

public sealed class ProjectScriptExporterTests
{
    [Fact]
    public void Export_EmitsProjectSetupAndTracks()
    {
        var project = new Project { Name = "Test Song", Tempo = new Tempo(140), BarCount = 8 };
        project.Tracks.Clear();
        var masterId = Guid.NewGuid();
        var kickId = Guid.NewGuid();
        project.Tracks.Add(new Track { Id = masterId, Name = "Master", Kind = TrackKind.Master, Volume = 1 });
        project.Tracks.Add(new Track { Id = kickId, Name = "Kick", Kind = TrackKind.Instrument });

        var script = new ProjectScriptExporter().Export(project);

        Assert.Contains("api.ClearProject()", script);
        Assert.Contains("api.SetProjectName(\"Test Song\")", script);
        Assert.Contains("api.SetTempo(140", script);
        Assert.Contains("api.AddMasterTrackWithId", script);
        Assert.Contains("api.AddInstrumentTrackWithId", script);
        Assert.Contains("Generated by Ongenet", script);
        Assert.DoesNotContain("Samples", script);
    }

    [Fact]
    public void Export_IncludesMidiNotes()
    {
        var project = new Project();
        project.Tracks.Clear();
        var track = new Track { Name = "Lead", Kind = TrackKind.Instrument };
        var clip = new Clip { Name = "Melody", StartBeat = 0, LengthBeats = 4, IsAudio = false };
        clip.Notes.Add(new MidiNote { Note = 60, StartBeat = 0, LengthBeats = 1, Velocity = 0.9f });
        track.Clips.Add(clip);
        project.Tracks.Add(new Track { Name = "Master", Kind = TrackKind.Master, Volume = 1 });
        project.Tracks.Add(track);

        var script = new ProjectScriptExporter().Export(project);
        Assert.Contains("api.AddMidiNotes", script);
        Assert.Contains("new ScriptMidiNote(60", script);
    }
}

public sealed class PresetScriptExporterTests
{
    [Fact]
    public void ExportInstrumentSlot_EmitsSetInstrument()
    {
        var registry = new InstrumentRegistry();
        var project = new Project();
        project.Tracks.Clear();
        var track = new Track { Name = "Kick", Kind = TrackKind.Instrument };
        track.Instruments.Add(new InstrumentSlot(registry.Create("kicka")) { Enabled = true });
        project.Tracks.Add(track);

        var script = new PresetScriptExporter().ExportInstrumentSlot(project, track.Id, 0);
        Assert.Contains("api.SetInstrument", script);
        Assert.Contains("kicka", script);
    }
}
