using System;
using System.Collections.Generic;

namespace Ongenet.Core.Services;

/// <summary>No-op scripting API for non-desktop heads.</summary>
public sealed class NullScriptingApi : IScriptingApi
{
    private static NotSupportedException Disabled() => new("Scripting is not enabled.");

    public IReadOnlyList<string> OutputLines => Array.Empty<string>();
    public event Action? OutputChanged { add { } remove { } }

    public void Log(string message) { }
    public void ClearOutput() { }
    public void ClearProject() => throw Disabled();
    public string GetProjectName() => string.Empty;
    public void SetProjectName(string name) => throw Disabled();
    public double GetTempo() => 120;
    public void SetTempo(double bpm) => throw Disabled();
    public ScriptTimeSignature GetTimeSignature() => new(4, 4);
    public void SetTimeSignature(int numerator, int denominator) => throw Disabled();
    public int GetBarCount() => 16;
    public void SetBarCount(int bars) => throw Disabled();
    public void SetKeySignature(int rootPitchClass, ScriptScaleType scale) => throw Disabled();
    public (int RootPitchClass, ScriptScaleType Scale) GetKeySignature() => (0, ScriptScaleType.Major);
    public ScriptPlaybackMode GetPlaybackMode() => ScriptPlaybackMode.Arrangement;
    public void SetPlaybackMode(ScriptPlaybackMode mode) => throw Disabled();
    public double GetLaunchQuantizeBeats() => 0;
    public void SetLaunchQuantizeBeats(double beats) => throw Disabled();
    public ScriptMpeSettings GetMpeSettings() => new(false, 1, 2, 14);
    public void SetMpeSettings(ScriptMpeSettings settings) => throw Disabled();
    public ScriptGrooveTemplate? GetActiveGroove() => null;
    public void SetActiveGroove(ScriptGrooveTemplate? groove) => throw Disabled();
    public ScriptTransportState GetTransportState() => ScriptTransportState.Stopped;
    public void Play() => throw Disabled();
    public void Stop() => throw Disabled();
    public void SeekToBeat(double beat) => throw Disabled();
    public double GetPlayheadBeats() => 0;
    public ScriptLoopRegion GetLoopRegion() => new(0, 0, false);
    public void SetLoopRegion(double start, double end) => throw Disabled();
    public void SetLoopActive(bool active) => throw Disabled();
    public IReadOnlyDictionary<Guid, string> GetTrackNames() => new Dictionary<Guid, string>();
    public IReadOnlyList<ScriptTrackInfo> GetTracks() => Array.Empty<ScriptTrackInfo>();
    public ScriptTrackInfo? GetTrack(Guid trackId) => null;
    public void RenameTrack(Guid trackId, string name) => throw Disabled();
    public Guid AddInstrumentTrack(string name) => throw Disabled();
    public Guid AddInstrumentTrackWithId(Guid id, string name, string? colorKey = null) => throw Disabled();
    public Guid AddAudioTrack(string name) => throw Disabled();
    public Guid AddAudioTrackWithId(Guid id, string name, string? colorKey = null) => throw Disabled();
    public Guid AddGroupTrack(string name) => throw Disabled();
    public Guid AddGroupTrackWithId(Guid id, string name, string? colorKey = null) => throw Disabled();
    public Guid AddReturnTrack(string name) => throw Disabled();
    public Guid AddReturnTrackWithId(Guid id, string name, string? colorKey = null) => throw Disabled();
    public Guid AddHybridTrack(string name) => throw Disabled();
    public Guid AddHybridTrackWithId(Guid id, string name, string? colorKey = null) => throw Disabled();
    public Guid AddMasterTrackWithId(Guid id, string name) => throw Disabled();
    public void RemoveTrack(Guid trackId) => throw Disabled();
    public void SetTrackVolume(Guid trackId, double volume) => throw Disabled();
    public void SetTrackPan(Guid trackId, double pan) => throw Disabled();
    public void SetTrackMuted(Guid trackId, bool muted) => throw Disabled();
    public void SetTrackSoloed(Guid trackId, bool soloed) => throw Disabled();
    public void SetTrackArmed(Guid trackId, bool armed) => throw Disabled();
    public void SetTrackColor(Guid trackId, string colorKey) => throw Disabled();
    public void SetTrackParent(Guid trackId, Guid? parentId) => throw Disabled();
    public void SetTrackSurroundWidth(Guid trackId, double width) => throw Disabled();
    public void SetTrackDrumMapId(Guid trackId, Guid? drumMapId) => throw Disabled();
    public IReadOnlyList<ScriptInstrumentInfo> GetInstruments(Guid trackId) => Array.Empty<ScriptInstrumentInfo>();
    public void SetInstrument(Guid trackId, int slotIndex, string typeId) => throw Disabled();
    public void RemoveInstrument(Guid trackId, int slotIndex) => throw Disabled();
    public void SetInstrumentEnabled(Guid trackId, int slotIndex, bool enabled) => throw Disabled();
    public void SetInstrumentParameter(Guid trackId, int slotIndex, string paramName, double value) => throw Disabled();
    public void SetInstrumentBoolParameter(Guid trackId, int slotIndex, string paramName, bool value) => throw Disabled();
    public void SetInstrumentChoiceParameter(Guid trackId, int slotIndex, string paramName, int choiceIndex) => throw Disabled();
    public void LoadInstrumentPreset(Guid trackId, int slotIndex, string presetName) => throw Disabled();
    public void SetInstrumentOutputBus(Guid trackId, int slotIndex, int busIndex, Guid? outputTrackId) => throw Disabled();
    public void SetComponentStateJson(Guid trackId, int slotIndex, int? effectIndex, string typeId, string stateJson) => throw Disabled();
    public IReadOnlyList<ScriptEffectInfo> GetEffects(Guid trackId, int instrumentSlotIndex = -1) => Array.Empty<ScriptEffectInfo>();
    public void AddEffect(Guid trackId, string typeId, int instrumentSlotIndex = -1) => throw Disabled();
    public void RemoveEffect(Guid trackId, int effectIndex, int instrumentSlotIndex = -1) => throw Disabled();
    public void SetEffectEnabled(Guid trackId, int effectIndex, bool enabled, int instrumentSlotIndex = -1) => throw Disabled();
    public void SetEffectParameter(Guid trackId, int effectIndex, string paramName, double value, int instrumentSlotIndex = -1) => throw Disabled();
    public void SetEffectBoolParameter(Guid trackId, int effectIndex, string paramName, bool value, int instrumentSlotIndex = -1) => throw Disabled();
    public void SetEffectChoiceParameter(Guid trackId, int effectIndex, string paramName, int choiceIndex, int instrumentSlotIndex = -1) => throw Disabled();
    public void LoadEffectPreset(Guid trackId, int effectIndex, string presetName, int instrumentSlotIndex = -1) => throw Disabled();
    public IReadOnlyList<ScriptClipInfo> GetClips(Guid? trackId = null) => Array.Empty<ScriptClipInfo>();
    public IReadOnlyList<ScriptMidiNote> GetMidiNotes(Guid clipId) => Array.Empty<ScriptMidiNote>();
    public ScriptAudioClipMetadata? GetAudioClipMetadata(Guid clipId) => null;
    public Guid CreateMidiClip(Guid trackId, string name, double startBeat, double lengthBeats) => throw Disabled();
    public Guid CreateMidiClipWithId(Guid id, Guid trackId, string name, double startBeat, double lengthBeats) => throw Disabled();
    public Guid CreateAudioClip(Guid trackId, string name, double startBeat, double lengthBeats, ScriptAudioClipMetadata metadata) => throw Disabled();
    public Guid CreateAudioClipWithId(Guid id, Guid trackId, string name, double startBeat, double lengthBeats, ScriptAudioClipMetadata metadata) => throw Disabled();
    public void DeleteClip(Guid clipId) => throw Disabled();
    public void MoveClip(Guid clipId, double startBeat) => throw Disabled();
    public void ResizeClip(Guid clipId, double lengthBeats) => throw Disabled();
    public Guid DuplicateClip(Guid clipId, double? offsetBeats = null) => throw Disabled();
    public void RenameClip(Guid clipId, string name) => throw Disabled();
    public void SetClipLinkedGroup(Guid clipId, Guid? groupId) => throw Disabled();
    public void ClearMidiNotes(Guid clipId) => throw Disabled();
    public void AddMidiNote(Guid clipId, ScriptMidiNote note) => throw Disabled();
    public void AddMidiNotes(Guid clipId, IReadOnlyList<ScriptMidiNote> notes) => throw Disabled();
    public void AddMidiControlChange(Guid clipId, ScriptMidiControlChange cc) => throw Disabled();
    public void ClearMidiControlChanges(Guid clipId) => throw Disabled();
    public void QuantizeAllMidiClips(double gridBeats) => throw Disabled();
    public void QuantizeClip(Guid clipId, double gridBeats) => throw Disabled();
    public void TransposeAllMidiClips(int semitones) => throw Disabled();
    public void ScaleAllMidiVelocities(double factor) => throw Disabled();
    public void HumanizeAllMidiClips(int maxTicks) => throw Disabled();
    public void ApplyChanceToAllMidiClips(float chance) => throw Disabled();
    public IReadOnlyList<ScriptAutomationLaneInfo> GetAutomationLanes(Guid trackId) => Array.Empty<ScriptAutomationLaneInfo>();
    public void AddAutomationLane(Guid trackId, ScriptAutomationBinding binding) => throw Disabled();
    public void ClearAutomationLane(Guid trackId, ScriptAutomationBinding binding) => throw Disabled();
    public void AddAutomationPoint(Guid trackId, ScriptAutomationBinding binding, ScriptAutomationPoint point) => throw Disabled();
    public void AddTrackModulator(Guid trackId, ScriptTrackModulatorInfo modulator) => throw Disabled();
    public IReadOnlyList<ScriptTrackSendInfo> GetSends(Guid trackId) => Array.Empty<ScriptTrackSendInfo>();
    public void AddSend(Guid trackId, Guid sendId, Guid targetTrackId, double level, bool preFader, bool enabled) => throw Disabled();
    public void SetSendLevel(Guid trackId, Guid sendId, double level) => throw Disabled();
    public IReadOnlyList<ScriptMultiOutputRouteInfo> GetMultiOutputRoutes() => Array.Empty<ScriptMultiOutputRouteInfo>();
    public void AddMultiOutputRoute(ScriptMultiOutputRouteInfo route) => throw Disabled();
    public IReadOnlyList<ScriptPatternInfo> GetPatterns() => Array.Empty<ScriptPatternInfo>();
    public Guid AddPatternWithId(Guid id, string name, double lengthBeats, int colorIndex) => throw Disabled();
    public void AddPatternChannel(Guid patternId, ScriptPatternChannelInfo channel) => throw Disabled();
    public void SetPatternSteps(Guid patternId, Guid channelId, IReadOnlyList<ScriptStepData> steps) => throw Disabled();
    public IReadOnlyList<ScriptPatternClipInfo> GetPatternClips() => Array.Empty<ScriptPatternClipInfo>();
    public void AddPatternClip(ScriptPatternClipInfo clip) => throw Disabled();
    public IReadOnlyList<ScriptSessionClipInfo> GetSessionClips() => Array.Empty<ScriptSessionClipInfo>();
    public void AddSessionClip(ScriptSessionClipInfo clip) => throw Disabled();
    public IReadOnlyList<ScriptMarkerInfo> GetMarkers() => Array.Empty<ScriptMarkerInfo>();
    public void AddMarker(ScriptMarkerInfo marker) => throw Disabled();
    public IReadOnlyList<ScriptSectionInfo> GetSections() => Array.Empty<ScriptSectionInfo>();
    public void AddSection(ScriptSectionInfo section) => throw Disabled();
    public IReadOnlyList<ScriptChordRegionInfo> GetChordRegions() => Array.Empty<ScriptChordRegionInfo>();
    public void SetChordTrackEnabled(bool enabled) => throw Disabled();
    public void AddChordRegion(ScriptChordRegionInfo region) => throw Disabled();
    public IReadOnlyList<ScriptDrumMapInfo> GetDrumMaps() => Array.Empty<ScriptDrumMapInfo>();
    public void AddDrumMap(ScriptDrumMapInfo map) => throw Disabled();
    public IReadOnlyList<ScriptExpressionMapInfo> GetExpressionMaps() => Array.Empty<ScriptExpressionMapInfo>();
    public void AddExpressionMap(ScriptExpressionMapInfo map) => throw Disabled();
    public IReadOnlyList<ScriptVideoLayerInfo> GetVideoLayers() => Array.Empty<ScriptVideoLayerInfo>();
    public void AddVideoLayer(ScriptVideoLayerInfo layer) => throw Disabled();
    public IReadOnlyList<ScriptVideoLayerItemInfo> GetVideoLayerItems() => Array.Empty<ScriptVideoLayerItemInfo>();
    public void AddVideoLayerItem(ScriptVideoLayerItemInfo item) => throw Disabled();
    public bool GetVideoEnabled() => false;
    public void SetVideoEnabled(bool enabled) => throw Disabled();
    public IReadOnlyList<ScriptVideoTriggerInfo> GetVideoTriggers() => Array.Empty<ScriptVideoTriggerInfo>();
    public void AddVideoTrigger(ScriptVideoTriggerInfo trigger) => throw Disabled();
    public IReadOnlyList<ScriptVideoVisibilityRegionInfo> GetVideoVisibilityRegions() => Array.Empty<ScriptVideoVisibilityRegionInfo>();
    public void AddVideoVisibilityRegion(ScriptVideoVisibilityRegionInfo region) => throw Disabled();
    public ScriptVideoCanvasInfo GetVideoCanvasSize() => new(1920, 1080, 30);
    public void SetVideoCanvasSize(ScriptVideoCanvasInfo size) => throw Disabled();
    public double GetVideoExportFps() => 30;
    public void SetVideoExportFps(double fps) => throw Disabled();
    public IReadOnlyList<ScriptControlRoomProfileInfo> GetControlRoomProfiles() => Array.Empty<ScriptControlRoomProfileInfo>();
    public void AddControlRoomProfile(ScriptControlRoomProfileInfo profile) => throw Disabled();
    public string ExportProjectAsScript(ExportScriptOptions? options = null) => throw Disabled();
    public string ExportInstrumentSlotAsScript(Guid trackId, int slotIndex, ExportScriptOptions? options = null) => throw Disabled();
    public string ExportEffectChainAsScript(Guid trackId, int instrumentSlotIndex = -1, ExportScriptOptions? options = null) => throw Disabled();
    public string ExportPresetAsScript(Guid trackId, int? slotIndex, int? effectIndex, ExportScriptOptions? options = null) => throw Disabled();
    public IDisposable OnTransportStateChanged(Action<ScriptTransportState> handler) => throw Disabled();
    public IDisposable OnBeat(Action<double> handler, double gridBeats = 1.0) => throw Disabled();
    public IDisposable OnClipChanged(Action<ScriptClipInfo> handler) => throw Disabled();
    public void StopLive() { }
}
